lecesse/base/urls.py
from django.conf.urls import url

from . import views

app_name = 'base'

urlpatterns = [
    #principal view
    url('index/', views.index, name='index'),
]

lecesse/lecesse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #direcciones del modulo base
    path('', include('base.urls')),
    #direcciones del modulo users
    path('users/', include('users.urls')),
    #direcciones del modulo phase one
    path('phase_one/', include('phase_one.urls')),
    #direcciones del modulo phase one
    path('phase_two/', include('phase_two.urls')),
    #redirige al index luego de hacer el login
    path('', RedirectView.as_view(url="/home/index/")),
    # muestra el login de inicio
	path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'),
        name='login'),
	#Logout
	path('logout/', auth_views.LogoutView.as_view(template_name='registration/login.html'),
        name='logout'),
]+ static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

lecesse/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    #principal view
    url('home/', views.home, name='home'),
    #edit user view
    url('edit-user/(?P<id_user>[0-9]+)/$', views.edit_user, name='edit_user'),
    #edit user view
    url('delete-user/(?P<id_user>[0-9]+)/$', views.delete_user, name='delete_user'),
    #user view
    url('view-user/(?P<id_user>[0-9]+)/$', views.view_user, name='view_user'),
]

lecesse/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from users.choices import ROLE_CHOICES

# Create your models here.


class CustomUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    document_number = models.CharField(max_length=150, null=False)
    phone_number = models.CharField(max_length=30, null=False)
    address = models.CharField(max_length=100, null=False)
    role = models.CharField(max_length=30, choices=ROLE_CHOICES, null=False)
    username = None
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

lecesse/users/forms.py
from django import forms
from users.models import CustomUser
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        exclude = ['id','last_login','username' ,'is_staff', 'is_superuser','user_permissions','is_active','date_joined']
        fields = ['first_name', 'last_name' ,'document_number','email', 'phone_number', 'address','password1', 'role', ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'document_number': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Document Number'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Phone Number'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
            'role': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Role'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
        }
        labels = {
            'first_name': ('First Name'),
            'last_name': ('Last Name'),
            'document_number': ('Number Document'),
            'phone_number': ('Number Phone'),
            'email': ('E-Mail'),
            'address': ('Address'),
            'role': ('Role'),
            'project': ('Project'),
            'password1': ('Password'),
        }
        help_texts = {
            'username': '',
            'is_active': '',
            'is_staff': '',
            'groups': '',
        }
    def clean_email(self):
        data = self.cleaned_data['email']
        return data.lower()


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        exclude = ['id', 'last_login', 'username', 'is_staff', 'is_superuser', 'user_permissions', 'is_active',
                   'date_joined']
        fields = ['first_name', 'last_name', 'document_number', 'email', 'phone_number', 'address', 'role',
                  ]
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'document_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'role': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'first_name': ('First Name'),
            'last_name': ('Last Name'),
            'document_number': ('Number Document'),
            'phone_number': ('Number Phone'),
            'email': ('E-Mail'),
            'address': ('Address'),
            'role': ('Role'),
        }
        help_texts = {
            'username': '',
            'is_active': '',
            'is_staff': '',
            'groups': '',
        }

    def clean_email(self):
        data = self.cleaned_data['email']
        return data.lower()

lecesse/users/views.py
from django.shortcuts import render, redirect
from users.forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.decorators import login_required
from users.models import CustomUser

# Create your views here.

@login_required(login_url='/login/')
def home(request):
    """show users view"""
    users = CustomUser.objects.all()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = form.save()
            return redirect('/users/home/')
        else:
            return render(request, 'users.html', {'form': form, 'users': users})
    else:
        form = CustomUserCreationForm()
        return render(request, 'users.html', {'form': form, 'users': users})


@login_required(login_url='/login/')
def edit_user(request, id_user):
    """allow edit a user"""
    user = CustomUser.objects.get(pk=id_user)

    if request.method == 'GET':
        # Get se usa para obtener datos y Post para enviar datos
        form = CustomUserChangeForm(instance=user)
    else:
        # Aqui guardamos el cliente
        form = CustomUserChangeForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('/users/home/')
    return render(request, 'edit_user.html', {'form': form})


@login_required(login_url='/login/')
def view_user(request, id_user):
    """can view data user"""
    user = CustomUser.objects.get(pk=id_user)
    return render(request, 'view_user.html', {'user': user})


@login_required(login_url='/login/')
def delete_user(request, id_user):
    """delete a user"""
    user = CustomUser.objects.get(pk=id_user)
    user.delete()
    return redirect('/users/home/')

lecesse/users/templates/edit_user.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
             <!-- Content Header (Page header) -->
             <section class="content-header mb-2">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">

                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="users.html">Users</a></li>
                                <li class="breadcrumb-item active">Edit</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>
            <section class="content-header mb-4" id="userEdit">
                <div class="container-fluid">
                    <div class="row mt-5">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-6 mt-1">

                            <div class="callout">
                                <h4 class="modal-title text-left ml-2 mb-3">Users Edit</h4>
                                <form role="form" method="post">
                                    {% csrf_token %}
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="form-group">
                                                    {{form}}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer text-right">
                                        <button type="button" class="btn btn-danger"
                                            data-dismiss="modal">Cancel</button> <button type="submit"
                                            class="btn btn-primary ml-4">Save</button>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>
</div>
{% endblock %}

lecesse/users/templates/users.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header mb-4">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">

                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="users.html">Users</a></li>
                                <li class="breadcrumb-item active">Create</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content" id="usersCreate">

                <!-- Default box -->
                <div>
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-md-4 ">
                                <small class="text-danger">
                            {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

      </small>
                                <form role="form" method="post" >
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-sm-2"></div>
                                        <div class="col-sm-8">
                                            <b class="text-center" style="color: #9E3639;">Create users</b>
                                            <div class="form-group mt-4">
                                                {{form}}
                                            </div>
                                            <button type="submit" class="btn btnSubcategory mt-2" style="color: #ffffff !important;
                                            font-size: .85em !important;">Create</button>
                                        </div>
                                        <div class="col-sm-2"></div>
                                    </div>

                                </form>
                            </div>
                            <div class="col-md-7">
                                <table class="table table-striped projects mt-5" style="background:#ffffff;">
                                    <thead>
                                        <tr>
                                            <th style="width: 20%">
                                                Name
                                            </th>
                                            <th style="width: 10%">
                                                Rol
                                            </th>
                                            <th style="width: 15%">
                                                Phone
                                            </th>
                                            <th style="width: 25%">
                                                email
                                            </th>
                                            <th style="width: 30%">
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for user in users %}
                                        <tr>
                                            <td>
                                                {{user.first_name}}
                                            </td>
                                            <td>
                                                {{user.role}}
                                            </td>
                                            <td>
                                                {{user.phone_number}}
                                            </td>
                                            <td>
                                                {{user.email}}
                                            </td>
                                            <td class="project-actions text-right">
                                                <a class="btn btn-primary btn-sm" href="{% url 'users:view_user' user.id  %}">
                                                    <i class="far fa-eye" style="color: #ffffff;"></i>
                                                </a>
                                                <a class="btn btn-info btn-sm" href="{% url 'users:edit_user' user.id  %}">
                                                    <i class="fas fa-pencil-alt" style="color:#ffffff;">
                                                    </i>
                                                </a>
                                                <a class="btn btn-danger btn-sm" href="{% url 'users:delete_user' user.id  %}">
                                                    <i class="fas fa-trash" style="color:#ffffff;">
                                                    </i>
                                                </a>
                                            </td>
                                        </tr>
                                         {% endfor %}
                                    </tbody>
                                </table>
                                <div class="row">
                                    <div class="col-sm-12 col-md-12">
                                        <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                                            <ul class="pagination">
                                                <li class="paginate_button page-item previous disabled"
                                                    id="example1_previous">
                                                    <a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0"
                                                        class="page-link">
                                                        Previous
                                                    </a>
                                                </li>
                                                <li class="paginate_button page-item active">
                                                    <a href="#" aria-controls="example1" data-dt-idx="1" tabindex="0"
                                                        class="page-link">
                                                        1
                                                    </a>
                                                </li>
                                                <li class="paginate_button page-item ">
                                                    <a href="#" aria-controls="example1" data-dt-idx="2" tabindex="0"
                                                        class="page-link">
                                                        2
                                                    </a>
                                                </li>
                                                <li class="paginate_button page-item next" id="example1_next">
                                                    <a href="#" aria-controls="example1" data-dt-idx="7" tabindex="0"
                                                        class="page-link">
                                                        Next
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-1"></div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </section>
            <!-- /.content -->
        </div>
{% endblock %}

lecesse/users/templates/view_user.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header mb-2">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">

                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="users.html">Users</a></li>
                                <li class="breadcrumb-item active">View details</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <section class="content-header mb-4">
                <div class="container-fluid">
                    <div class="row mt-5">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-6 mt-1">

                            <div class="callout">
                                <h4 class="modal-title text-left ml-2 mb-3">Users Details</h4>

                                <form role="form mt-4">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="infoGroup">
                                                    <h5>Name</h5>
                                                    <p>{{ user.first_name}}</p>
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="infoGroup">
                                                    <h5>Last Name</h5>
                                                    <p>{{ user.last_name}}</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row mt-3" >
                                            <div class="col-sm-6">
                                                <div class="infoGroup">
                                                    <h5>Number Document</h5>
                                                    <p>{{user.document_number}}</p>
                                                </div>
                                            </div>

                                            <div class="col-sm-6">
                                                <div class="infoGroup">
                                                    <h5>Roles User</h5>
                                                    <p>{{ user.role}}</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row mt-3">
                                            <div class="col-sm-6">
                                                <div class="infoGroup">
                                                    <h5>Phone</h5>
                                                    <p>{{user.phone_number}}</p>
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="infoGroup">
                                                    <h5>Email</h5>
                                                    <p>{{user.email}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>
</div>
{% endblock %}