lecesse/base/urls.py
from django.conf.urls import url

from . import views

app_name = 'base'

urlpatterns = [
    #principal view
    url('index/', views.index, name='index'),
]

lecesse/lecesse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #direcciones del modulo base
    path('', include('base.urls')),
    #direcciones del modulo users
    path('users/', include('users.urls')),
    #direcciones del modulo phase one
    path('phase_one/', include('phase_one.urls')),
    #direcciones del modulo phase one
    path('phase_two/', include('phase_two.urls')),
    #redirige al index luego de hacer el login
    path('', RedirectView.as_view(url="/home/index/")),
    # muestra el login de inicio
	path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'),
        name='login'),
	#Logout
	path('logout/', auth_views.LogoutView.as_view(template_name='registration/login.html'),
        name='logout'),
]+ static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

lecesse/phase_one/urls.py
from django.conf.urls import url

from . import views

app_name = 'phase_one'

urlpatterns = [
    #principal view
    url('home/', views.home, name='home'),
    #view category
    url('category/', views.category, name='category'),
    url('edit-cate/(?P<id_category>[0-9]+)/$', views.edit_cate, name='edit_cate'),
    url('delete-cate/(?P<id_category>[0-9]+)/$', views.delete_cate, name='delete_cate'),
    url('view_cate/(?P<id_category>[0-9]+)/$', views.view_cate, name='view_cate'),

    #view materials
    url('materials/', views.materials, name='materials'),
    url('edit-material/(?P<id_material>[0-9]+)/$', views.edit_material, name='edit_material'),
    url('delete-material/(?P<id_material>[0-9]+)/$', views.delete_material, name='delete_material'),
    url('view_material/(?P<id_material>[0-9]+)/$', views.view_material, name='view_material'),

    #view providers
    url('providers/', views.providers, name='providers'),
    url('edit-provider/(?P<id_provider>[0-9]+)/$', views.edit_provider, name='edit_provider'),
    url('delete-provider/(?P<id_provider>[0-9]+)/$', views.delete_provider, name='delete_provider'),
    url('view_provider/(?P<id_provider>[0-9]+)/$', views.view_provider, name='view_provider'),


]

lecesse/phase_one/forms.py
from django import forms
from phase_one.models import *

class SubcategoryTwoForm(forms.ModelForm):
    class Meta:
        model = SubcategoryTwo
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': ('Subcategory Two '),
        }


class SubcategoryTwo_Edit_Form(forms.ModelForm):
    class Meta:
        model = SubcategoryTwo
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': ('Subcategory Two '),
        }


class SubcategoryForm(forms.ModelForm):
    class Meta:
        model = Subcategory
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': ('Subcategory '),
        }


class Subcategory_Edit_Form(forms.ModelForm):
    class Meta:
        model = Subcategory
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': ('Name '),
        }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'subcategory','subcategory_two']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'subcategory': forms.Select(attrs={'class': 'form-control'}),
            'subcategory_two': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': ('Name '),
            'subcategory': ('Subcategory'),
        }


class Category_Edit_Form(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'subcategory','subcategory_two']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'subcategory': forms.Select(attrs={'class': 'form-control'}),
            'subcategory_two': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': ('Name '),
            'subcategory': ('Subcategory'),
        }


class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['name', 'reference', 'description', 'color', 'price', 'measured_type', 'area_total',
                  'image', 'environment', 'category']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Name'}),
            'reference': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Reference'}),
            'description': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Description'}),
            'color': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Color'}),
            'price': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Price'}),
            'measured_type': forms.Select(attrs={'class': 'form-control','placeholder': 'Measured Type'}),
            'area_total': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Area'}),
            'environment': forms.Select(attrs={'class': 'form-control','placeholder': 'Environment'}),
            'category': forms.Select(attrs={'class': 'form-control','placeholder': 'Category'}),
        }


class Material_Edit_Form(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['name', 'reference', 'description', 'color', 'price', 'measured_type', 'area_total',
                  'image', 'environment', 'category']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Name'}),
            'reference': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Reference'}),
            'description': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Description'}),
            'color': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Color'}),
            'price': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Price'}),
            'measured_type': forms.Select(attrs={'class': 'form-control','placeholder': 'Measured Type'}),
            'area_total': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Area'}),
            'environment': forms.Select(attrs={'class': 'form-control','placeholder': 'Environment'}),
            'category': forms.Select(attrs={'class': 'form-control','placeholder': 'Category'}),
        }


class ProviderForm(forms.ModelForm):
    class Meta:
        model = Provider
        fields = ['name', 'phone_number', 'email', 'address_company',
                  'activity', 'state', 'zip_code','material']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Name'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control','placeholder': 'Phone Number'}),
            'email': forms.EmailInput(attrs={'class': 'form-control','placeholder': 'Email'}),
            'address_company': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Address'}),
            'activity': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Activity'}),
            'state': forms.TextInput(attrs={'class': 'form-control','placeholder': 'State'}),
            'zip_code': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Zip Code'}),
            'material': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Material'}),
        }
        labels = {
            'name': ('Name'),
            'phone_number': ('Phone Number '),
            'email': ('Email'),
            'address_company': ('Address Company'),
            'activity': ('Activity'),
            'state': ('State'),
            'zip_code': ('Zip Code'),

        }


class Provider_Edit_Form(forms.ModelForm):
    class Meta:
        model = Provider
        fields = ['name', 'phone_number', 'email', 'address_company', 'activity',
                  'state', 'zip_code', 'material']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Name'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control','placeholder': 'Phone Number'}),
            'email': forms.EmailInput(attrs={'class': 'form-control','placeholder': 'Email'}),
            'address_company': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Address'}),
            'activity': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Activity'}),
            'state': forms.TextInput(attrs={'class': 'form-control','placeholder': 'State'}),
            'zip_code': forms.TextInput(attrs={'class': 'form-control','placeholder': 'Zip Code'}),
            'material': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Material'}),

        }
        labels = {
            'name': ('Name'),
            'phone_number': ('Phone Number '),
            'email': ('Email'),
            'address_company': ('Address Company'),
            'activity': ('Activity'),
            'state': ('State'),
            'zip_code': ('Zip Code'),
            'contact': ('Contact'),
        }

lecesse/phase_one/views.py
from django.shortcuts import render, redirect
from phase_one.models import *
from phase_one.forms import SubcategoryForm,SubcategoryTwoForm, \
    CategoryForm, Category_Edit_Form, MaterialForm, Material_Edit_Form, ProviderForm, Provider_Edit_Form
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login/')
def home(request):
    """show phase one view"""
    materials = Material.objects.all()
    return render(request, 'index_phase_one.html',{'materials':materials})

@login_required(login_url='/login/')
def category(request):
    """show category view"""
    categories = Category.objects.all()
    if request.method == 'POST' and 'btnform1' in request.POST:
        form_subcategory = SubcategoryForm(request.POST)
        if form_subcategory.is_valid():
            data_subcategory = form_subcategory.save()
            return redirect('phase_one/category/')
        else:
            return render(request, 'category.html', {'form_subcategory': form_subcategory})
    if request.method == 'POST' and 'btnform2' in request.POST:
        form_subcategoryTwo = SubcategoryTwoForm(request.POST)
        if form_subcategoryTwo.is_valid():
            data_subcategory = form_subcategoryTwo.save()
            return redirect('phase_one/category/')
        else:
            return render(request, 'category.html', {'form_subcategoryTwo': form_subcategoryTwo})
    if request.method == 'POST' and 'btnform3' in request.POST:
        form_category = CategoryForm(request.POST)
        if form_category.is_valid():
            data_category = form_category.save()
            return redirect('phase_one/category/')
        else:
            return render(request, 'category.html', {'form_category': form_category})
    else:
        form_subcategory = SubcategoryForm()
        form_subcategoryTwo = SubcategoryTwoForm()
        form_category = CategoryForm()
        return render(request, 'category.html', {'form_subcategory': form_subcategory,
                                                'form_category': form_category,
                                                 'form_subcategoryTwo':form_subcategoryTwo,
                                                 'categories': categories})

@login_required(login_url='/login/')
def view_cate(request, id_category):
    """can view data enviroment"""
    category = Category.objects.get(pk=id_category)
    return render(request, 'view_category.html', {'category': category})

@login_required(login_url='/login/')
def edit_cate(request, id_category):
    """can edit a enviroment"""
    category = Category.objects.get(pk=id_category)
    if request.method == 'GET':
        # Get se usa para obtener datos y Post para enviar datos
        form = Category_Edit_Form(instance=category)
    else:
        # Aqui guardamos el cliente
        form = Category_Edit_Form(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('phase_one/category/')
    return render(request, 'edit_category.html', {'form': form})

@login_required(login_url='/login/')
def delete_cate(request, id_category):
    """delete a category"""
    category = Category.objects.get(pk=id_category)
    category.delete()
    return redirect('phase_one/category/')

@login_required(login_url='/login/')
def materials(request):
    """show materials view"""
    materials = Material.objects.all()
    if request.method == 'POST':
        form_material = MaterialForm(request.POST, request.FILES)
        if form_material.is_valid():
            form_material.save()
            return redirect('phase_one/materials/')
        else:
            print("formulario no valido")
            print(form_material)
            return render(request, 'materials.html', {'form_material': form_material, 'materials':materials})
    else:
        form_material = MaterialForm()
        return render(request, 'materials.html', {'form_material': form_material, 'materials':materials})


@login_required(login_url='/login/')
def view_material(request, id_material):
    """can view data enviroment"""
    material = Material.objects.get(pk=id_material)
    return render(request, 'view_material.html', {'material': material})

@login_required(login_url='/login/')
def edit_material(request, id_material):
    """can edit a enviroment"""
    material = Material.objects.get(pk=id_material)

    if request.method == 'GET':
        # Get se usa para obtener datos y Post para enviar datos
        form = Material_Edit_Form(instance=material)
    else:
        # Aqui guardamos el cliente
        form = Material_Edit_Form(request.POST or None, request.FILES or None, instance=material)
        if form.is_valid():
            form.save()
            return redirect('phase_one/materials/')
    return render(request, 'edit_material.html', {'form': form})

@login_required(login_url='/login/')
def delete_material(request, id_material):
    """delete a category"""
    material = Material.objects.get(pk=id_material)
    material.delete()
    return redirect('phase_one/materials/')

@login_required(login_url='/login/')
def providers(request):
    """show providers view"""
    providers = Provider.objects.all()
    if request.method == 'POST':
        form_provider = ProviderForm(request.POST)
        if form_provider.is_valid():
            form_provider.save()
            return redirect('/phase_one/providers/')
        else:
            print("formulario no valido")
            print(form_provider)
            return render(request, 'providers.html', {'form_provider': form_provider, 'providers': providers})
    else:
        form_provider = ProviderForm()
        return render(request, 'providers.html', {'form_provider': form_provider, 'providers': providers})

@login_required(login_url='/login/')
def view_provider(request, id_provider):
    """can view data enviroment"""
    provider = Provider.objects.get(pk=id_provider)
    return render(request, 'view_provider.html', {'provider': provider})

@login_required(login_url='/login/')
def edit_provider(request, id_provider):
    """can edit a enviroment"""
    provider = Provider.objects.get(pk=id_provider)

    if request.method == 'GET':
        # Get se usa para obtener datos y Post para enviar datos
        form = Provider_Edit_Form(instance=provider)
    else:
        # Aqui guardamos el cliente
        form = Provider_Edit_Form(request.POST, instance=provider)
        if form.is_valid():
            form.save()
            return redirect('/phase_one/providers/')
    return render(request, 'edit_provider.html', {'form': form})

@login_required(login_url='/login/')
def delete_provider(request, id_provider):
    """delete a category"""
    provider = Provider.objects.get(pk=id_provider)
    provider.delete()
    return redirect('/phase_one/providers/')

lecesse/phase_one/templates/edit_category.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header mb-2">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">

                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="users.html">Category</a></li>
                                <li class="breadcrumb-item active">Edit details</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <section class="content-header mb-4">
                <div class="container-fluid">
                    <div class="row mt-5">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-6 mt-1">

                            <div class="callout">
                                <h4 class="modal-title text-left ml-2 mb-3">Category Details</h4>

                                <form role="form mt-4" method="post">
                                    {% csrf_token %}
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <div class="infoGroup">
                                                    <h5>Name</h5>
                                                    <p>{{ form.name}}</p>
                                                </div>
                                            </div>
                                            <div class="col-sm-6">
                                                <div class="infoGroup">
                                                    <h5>Last Name</h5>
                                                    <p>{{ form.subcategory}}</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row mt-3" >
                                            <div class="col-sm-6">
                                                <div class="infoGroup">
                                                    <h5>Number Document</h5>
                                                    <p>{{form.subcategory_two}}</p>
                                                </div>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-secondary btn-xs mt-2">Save</button>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>
</div>
{% endblock %}

lecesse/phase_one/templates/index_phase_one.html
{% extends 'base_phase_one.html' %}
{% block form %}
  <div class="card-header mt-5">
    <div class="row">
        <div class="col-md-7"></div>
        <div class="col-md-5">
            <div class="form-group">
                <div class="input-group-prepend" >
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
                    &nbsp;&nbsp;
                    <button type="button" class="btn  btn-secondary btn-xs">Import</button>
                </div>
            </div>

        </div>


    </div>
  </div>

  <div class="card-body table-responsive p-0">
    <table class="table table-striped projects mt-3" style="background:#ffffff;">
        <thead>
            <tr>

                <th style="width: 15%">
                    Name
                </th>
                <th style="width: 15%">
                    Reference
                </th>
                <th style="width: 15%">
                    Category
                </th>
                <th style="width: 25%">
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                        {% for material in materials %}
                        <td>
                            {{ forloop.counter}}
                        </td>
                        <td>
                           {{ material.name}}
                        </td>
                        <td>
                           {{ material.reference}}
                        </td>
                        <td>
                            {{ material.category}}
                        </td>

                         <td class="project-actions text-right">
                             <a class="btn btn-info btn-sm" href="{% url 'phase_one:view_material' material.id  %}">
                                 <i class="fas fa-eye" style="color: #ffffff;">
                                 </i>
                             </a>
                             <a class="btn btn-info btn-sm" href="{% url 'phase_one:edit_material' material.id  %}">
                                 <i class="fas fa-pencil-alt" style="color: #ffffff;">
                                 </i>
                             </a>
                             <a class="btn btn-danger btn-sm" href="{% url 'phase_one:delete_material' material.id  %}">
                                 <i class="fas fa-trash" style="color: #ffffff;">
                                 </i>
                             </a>
                            </td>
                        {% endfor %}
                    </tr>

        </tbody>
    </table>
  </div>

</div>
{% endblock %}

lecesse/phase_one/templates/materials.html
{% extends 'base_phase_one.html' %}
{% block form %}
<div class="card-body mt-5 p-0">
    <div class="row">
        <div class="col-md-5">
            <form role="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm-10">
                        <b class="text-center" style="color: #000;">Create
                            Material</b>

                        <div class="form-group mt-3">
                            <div class="input-group">
                                {{form_material.name}}&nbsp;
                                {{form_material.reference}}
                            </div>
                        </div>

                        <div class="form-group">
                            {{form_material.description}}
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                {{form_material.color}}&nbsp;
                               {{form_material.price}}
                            </div>
                        </div>
                        <div class="form-group">
                            {{form_material.measured_type}}
                        </div>

                        <div class="form-group" id="materialGroup">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span style="font-size: .85rem !important;">Area&nbsp;</span>
                                </div>
                                <div class="input-group-prepend">
                                    <input type="text" size=1 class="form-control monto" name="Precio" id="Precio" value="" onkeyup="multi();">
                                    <span>&nbsp;x&nbsp;</span>
                                    <input type="text" size=1 class="form-control monto" name="Cantidad" id="Cantidad" onkeyup="multi();">
                                </div><span>&nbsp;=&nbsp;</span>
                                      <input type="hidden" name="area_total" id="area_total">
                                 <label id="Resultado">
                                 </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <div class="custom-file">
                                    {{form_material.image}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                {{form_material.environment}}&nbsp;
                                 {{form_material.category}}
                            </div>
                        </div>
                        <button type="submit"
                            class="btn btnMaterials mt-2">Create</button>
                    </div>
                    <div class="col-sm-2"></div>
                </div>

            </form>
        </div>
        <div class="col-md-7">
            <p class="text-right"><button class="btn btn-flat btn-sm" style="background: #001D2C;color: #fff;">Exportar</button></p>
            <table class="table table-striped projects mt-3" style="background:#ffffff;">
                <thead>
                    <tr>
                        <th style="width: 5%">
                            ID
                        </th>
                        <th style="width: 20%">
                            Name
                        </th>
                        <th style="width: 10%">
                            Reference
                        </th>
                        <th style="width: 15%">
                            Category
                        </th>
                        <th style="width: 40%">
                        </th>
                    </tr>
                </thead>
                <tbody>

                        {% for material in materials %}
                         <tr>
                        <td>
                            {{ forloop.counter}}
                        </td>
                        <td>
                           {{ material.name}}
                        </td>
                        <td>
                           {{ material.reference}}
                        </td>
                        <td>
                            {{ material.category}}
                        </td>

                         <td class="project-actions text-right">
                             <a class="btn btn-info btn-sm" href="{% url 'phase_one:view_material' material.id  %}">
                                 <i class="fas fa-eye" style="color: #ffffff;">
                                 </i>
                             </a>
                             <a class="btn btn-info btn-sm" href="{% url 'phase_one:edit_material' material.id  %}">
                                 <i class="fas fa-pencil-alt" style="color: #ffffff;">
                                 </i>
                             </a>
                             <a class="btn btn-danger btn-sm" href="{% url 'phase_one:delete_material' material.id  %}">
                                 <i class="fas fa-trash" style="color: #ffffff;">
                                 </i>
                             </a>
                            </td>
                         </tr>
                        {% endfor %}

                </tbody>
            </table>
            <div class="row">
                <div class="col-sm-12 col-md-12">
                    <div class="dataTables_paginate paging_simple_numbers"
                        id="example1_paginate">
                        <ul class="pagination">
                            <li class="paginate_button page-item previous disabled"
                                id="example1_previous">
                                <a href="#" aria-controls="example1" data-dt-idx="0"
                                    tabindex="0" class="page-link">
                                    Previous
                                </a>
                            </li>
                            <li class="paginate_button page-item active">
                                <a href="#" aria-controls="example1" data-dt-idx="1"
                                    tabindex="0" class="page-link">
                                    1
                                </a>
                            </li>
                            <li class="paginate_button page-item ">
                                <a href="#" aria-controls="example1" data-dt-idx="2"
                                    tabindex="0" class="page-link">
                                    2
                                </a>
                            </li>
                            <li class="paginate_button page-item next" id="example1_next">
                                <a href="#" aria-controls="example1" data-dt-idx="7"
                                    tabindex="0" class="page-link">
                                    Next
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
function multi(){
    var total = 1;
    var change= false; //
    $(".monto").each(function(){
        if (!isNaN(parseFloat($(this).val()))) {
            change= true;
            total *= parseFloat($(this).val());
        }
    });

    total = (change)? total:0;
    document.getElementById('Resultado').innerHTML = total;
    $("#area_total").val(total);
}
</script>
{% endblock %}