lecesse/base/urls.py
from django.conf.urls import url

from . import views

app_name = 'base'

urlpatterns = [
    #principal view
    url('index/', views.index, name='index'),
]

lecesse/lecesse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #direcciones del modulo base
    path('', include('base.urls')),
    #direcciones del modulo users
    path('users/', include('users.urls')),
    #direcciones del modulo phase one
    path('phase_one/', include('phase_one.urls')),
    #direcciones del modulo phase one
    path('phase_two/', include('phase_two.urls')),
    #redirige al index luego de hacer el login
    path('', RedirectView.as_view(url="/home/index/")),
    # muestra el login de inicio
	path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'),
        name='login'),
	#Logout
	path('logout/', auth_views.LogoutView.as_view(template_name='registration/login.html'),
        name='logout'),
]+ static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

lecesse/phase_one/urls.py
from django.conf.urls import url

from . import views

app_name = 'phase_one'

urlpatterns = [
    #principal view
    url('home/', views.home, name='home'),
    #view category
    url('category/', views.category, name='category'),
    url('edit-cate/(?P<id_category>[0-9]+)/$', views.edit_cate, name='edit_cate'),
    url('delete-cate/(?P<id_category>[0-9]+)/$', views.delete_cate, name='delete_cate'),
    url('view_cate/(?P<id_category>[0-9]+)/$', views.view_cate, name='view_cate'),

    #view materials
    url('materials/', views.materials, name='materials'),
    url('edit-material/(?P<id_material>[0-9]+)/$', views.edit_material, name='edit_material'),
    url('delete-material/(?P<id_material>[0-9]+)/$', views.delete_material, name='delete_material'),
    url('view_material/(?P<id_material>[0-9]+)/$', views.view_material, name='view_material'),

    #view providers
    url('providers/', views.providers, name='providers'),
    url('edit-provider/(?P<id_provider>[0-9]+)/$', views.edit_provider, name='edit_provider'),
    url('delete-provider/(?P<id_provider>[0-9]+)/$', views.delete_provider, name='delete_provider'),
    url('view_provider/(?P<id_provider>[0-9]+)/$', views.view_provider, name='view_provider'),


]

lecesse/phase_two/urls.py
from django.conf.urls import url

from . import views

app_name = 'phase_two'

urlpatterns = [
    #principal view
    url('home/', views.home, name='home'),
    #view category
    url('environments/', views.environment, name='environments'),
    url('edit-enviroment/(?P<id_enviroment>[0-9]+)/$', views.edit_enviroment, name='edit_enviroment'),
    url('delete-enviroment/(?P<id_enviroment>[0-9]+)/$', views.delete_enviroment, name='delete_enviroment'),
    url('view-enviroment/(?P<id_enviroment>[0-9]+)/$', views.view_enviroment, name='view_enviroment'),

    #view materials
    url('model_apartment/', views.model_apartment, name='model_apartment'),
    url('create_apartment/', views.create_apartment, name='create_apartment'),
    url('create_apartment_tree/', views.create_apartment_tree, name='create_apartment_tree'),
    url('create_apartment_finish/', views.create_apartment_finish, name='create_apartment_finish'),
    url('edit-apartment/(?P<id_apartment>[0-9]+)/$', views.edit_apartment, name='edit_apartment'),
    url('delete-apartment/(?P<id_apartment>[0-9]+)/$', views.delete_apartment, name='delete_apartment'),
    url('view_apartment/(?P<id_apartment>[0-9]+)/$', views.view_apartment, name='view_apartment'),


    #view providers
    url('project/', views.project, name='project'),
    url('create_pro/', views.create_pro, name='create_pro'),
    url('edit-pro/(?P<id_project>[0-9]+)/$', views.edit_pro, name='edit_pro'),
    url('delete-pro/(?P<id_project>[0-9]+)/$', views.delete_pro, name='delete_pro'),
    url('view_pro/(?P<id_project>[0-9]+)/$', views.view_pro, name='view_pro'),

    #contact
    url('create_cont/', views.create_cont, name='create_cont'),



    url('create_building/', views.create_building, name='create_building'),

    url('finish_pro/', views.finish_pro, name='finish_pro'),

]

lecesse/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    #principal view
    url('home/', views.home, name='home'),
    #edit user view
    url('edit-user/(?P<id_user>[0-9]+)/$', views.edit_user, name='edit_user'),
    #edit user view
    url('delete-user/(?P<id_user>[0-9]+)/$', views.delete_user, name='delete_user'),
    #user view
    url('view-user/(?P<id_user>[0-9]+)/$', views.view_user, name='view_user'),
]

lecesse/base/models.py
from django.db import models


# Create your models here.

lecesse/base/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='/login/')
def index(request):
    """show index view"""
    return render(request, 'index.html')

lecesse/base/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&display=swap"
        rel="stylesheet">

    <!-- Font Awesome -->
     {% block css %}
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />

    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!--STYLE personal-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}

</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- *****************
        Header Menu top
        *****************-->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
                <li><img src="{% static 'img/logo.png' %}" alt=""></li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                              <!--Notification Drop-->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="fas fa-bell" style="color: #ffffff;"></i>
                        <span class="badge badge-warning navbar-badge">15</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-envelope mr-2"></i> 4 new project
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i> 8 users created
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="notification.html" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>

                <!-- Config Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#" style="border-left:.5px solid #ffffff;">
                        <i class="fas fa-cog" style="color: #ffffff;"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu dropdown-menu-right">

                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i>Users
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'logout' %}" class="dropdown-item">
                            <i class="fas fa-sign-out-alt mr-2"></i> Out
                        </a>
                    </div>
                </li>

            </ul>
        </nav>

        <!-- *****************
        Slidebar Right
        **********************-->
        <aside class="main-sidebar sidebar-dark-primary elevation-4" style="background-color: #061741;">
            <!-- Brand Logo -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex" style="    float: left;">
                <div class="image">
                    <img src="{% static 'img/iconAdmin.png' %}" class="img-circle" alt="User Image">
                </div>

            </div>

            <div class="info">
                <li class="nav-item dropdown" style="list-style: none; padding: 1em;">
                    <a href="#" data-toggle="dropdown" style="color: #ffffff; padding-left: 1em;"> Alexander Pierce
                        &nbsp;&nbsp;&nbsp;<i class="fas fa-sort-down"></i></a>
                    <div class="dropdown-menu">
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i>Edit
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-sign-out-alt mr-2"></i> Out
                        </a>
                    </div>
                </li>
            </div>
            <hr>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar Menu -->
                <nav class="menuLeft">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                        <br>
                        <li class="nav-item active">
                            <a href="{% url 'base:index' %}" class="nav-link">
                                <i class="nav-icon fas fa-home" style="color:#ababab;"></i>
                                <p style="color:#ababab;">
                                    Home
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="{% url 'phase_one:home' %}" class="nav-link">
                                <i class="nav-icon fas fa-file-signature" style="color:#ababab;"></i>
                                <p style="color:#ababab;">
                                    Materials
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="{% url 'phase_two:home' %}" class="nav-link">
                                <i class="nav-icon fas fa-building" style="color:#ababab;"></i>
                                <p style="color:#ababab;">
                                    Projects
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="faseTres.html" class="nav-link">
                                <i class="nav-icon fas fa-calendar-check" style="color:#ababab;"></i>
                                <p style="color:#ababab;">
                                    Schedule
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="{% url 'users:home' %}" class="nav-link">
                                <i class="nav-icon fas fa-users" style="color:#ababab;"></i>
                                <p style="color:#ababab;">
                                    Users
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="contractor.html" class="nav-link">
                                <i class="nav-icon far fa-address-card" style="color:#ababab;"></i>
                                <p style="color:#ababab;">
                                    Contractor
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="notification.html" class="nav-link">
                                <i class="nav-icon fas fa-bell" style="color:#ababab;"></i>
                                <p style="color:#ababab;">
                                    Notification
                                </p>
                            </a>
                        </li>

                        <li class="nav-item has-treeview">
                            <a href="dashboard.html" class="nav-link">
                                <i class="nav-icon fas fa-chart-bar" style="color:#ababab;"></i>
                                <p style="color:#ababab;">
                                    Dashboard
                                </p>
                            </a>
                        </li>

                        <li class="nav-item has-treeview">
                            <a href="setting.html" class="nav-link">
                                <i class="nav-icon fas fa-tools" style="color:#ababab;"></i>
                                <p style="color:#ababab;">
                                    Setting
                                </p>
                            </a>
                        </li>

                        <li class="nav-item has-treeview" style="margin-top:8em;">
                            <a href="help.html" class="nav-link">
                                <i class="nav-icon fas fa-comments" style="color:#ababab;"></i>
                                <p style="color:#ababab;">
                                    Help
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

<!-- ***********************
Content page
****************************** -->
        <div>
            {% block content %}


        {% endblock %}
        </div>



    </div>
    <!-- ./wrapper -->

    <!-- AdminLTE App -->
     {% block js %}
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/adminlte.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'js/pages/dashboard.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'js/demo.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
     {% endblock %}
</body>

</html>

lecesse/base/templates/base_phase_one.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
            <!--Miga-->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">

                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">

                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!--Contenido-->
            <div class="row mt-3">
                <div class="col-lg-1 col-md-1"></div>
                <div class="col-lg-10 col-md-10">
                    <!-- Nav tabs -->
                    <ul class="nav nav-pills nav-justified" id="TabFaseUno" role="tablist">
                        <li class="nav-item">
                            <a href="{% url 'phase_one:home' %}" role="tab"
                                aria-controls="all" aria-selected="false">All</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'phase_one:category' %}" role="tab"
                                aria-controls="category" aria-selected="false">Category</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'phase_one:materials' %}" role="tab"
                                aria-controls="all" aria-selected="false">Materials</a>
                        </li>
                        <li class="nav-item">
                            <a  class=nav-link" href="{% url 'phase_one:providers' %}" role="tab"
                                aria-controls="category" aria-selected="false">Providers</a>
                        </li>

                    </ul>

                    <!-- Tab panes -->
                    <div >
                     {% block form %} {% endblock %}
                    </div>

                </div>
                <div class="col-lg-1 col-md-1"></div>
            </div>
            </div>
{% endblock %}

lecesse/base/templates/base_phase_two.html
{% extends 'base.html' %}
{% block content %}
<div class="content-wrapper">
            <!--Miga-->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">

                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">

                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!--Contenido-->
            <div class="row mt-3">
                <div class="col-lg-1 col-md-1"></div>
                <div class="col-lg-10 col-md-10">
                    <!-- Nav tabs -->
                    <ul class="nav nav-pills nav-justified" id="TabFaseUno" role="tablist">
                        <li class="nav-item">
                            <a href="{% url 'phase_two:home' %}" role="tab"
                                aria-controls="all" aria-selected="false">All</a>
                        </li>
                        <li class="nav-item">
                            <a  href="{% url 'phase_two:environments' %}" role="tab"
                                aria-controls="category" aria-selected="false">Environments</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'phase_two:model_apartment' %}" role="tab"
                                aria-controls="all" aria-selected="false">Model Apto</a>
                        </li>
                        <li class="nav-item">
                            <a  class=nav-link" href="{% url 'phase_two:project' %}" role="tab"
                                aria-controls="category" aria-selected="false">Project</a>
                        </li>

                    </ul>

                    <!-- Tab panes -->
                    <div >
                     {% block form %} {% endblock %}
                    </div>

                </div>
                <div class="col-lg-1 col-md-1"></div>
            </div>
            </div>
{% endblock %}

lecesse/base/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-wrapper">
            <!-- Main content -->
            <section class="content">
                <div class="container">
                    <div class="container">
                        <!-- Small boxes (Stat box) -->
                        <div class="row" style="padding-top:5em;">
                            <!-- ./col -->
                            <div class="col-md-3"> </div>
                            <div class="col-md-2">
                                <!-- small box -->
                                <div class="small-box bg-info" style="background-color: #fff!important;">

                                    <button type="button" class="btn btn-default" role="link" onclick="window.location='{% url 'phase_one:home' %}'">
                                        Materials
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <!-- small box -->
                                <div class="small-box bg-info" style="background-color: #fff!important;">
                                    <button type="button" class="btn btn-default" role="link" onclick="window.location='{% url 'phase_two:home' %}'">
                                        Projects
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <!-- small box -->
                                <div class="small-box bg-info" style="background-color: #fff!important;">
                                    <button type="button" class="btn btn-default" role="link" onclick="window.location='faseTres.html'">
                                        Schedule
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-3"> </div>

                            <div class="col-md-3"> </div>
                            <div class="col-md-2">
                                <!-- small box -->
                                <div class="small-box bg-info" style="background-color: #fff!important;">

                                    <button type="button" class="btn btn-default" role="link" onclick="window.location='providers.html'">
                                        Providers
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <!-- small box -->
                                <div class="small-box bg-info" style="background-color: #fff!important;">
                                    <button type="button" class="btn btn-default" role="link" onclick="window.location='{% url 'users:home' %}'">
                                        Users
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <!-- small box -->
                                <div class="small-box bg-info" style="background-color: #fff!important;">
                                    <button type="button" class="btn btn-default" role="link" onclick="window.location='dashboard.html'">
                                        Dashboard
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-3"> </div>

                            <div class="col-md-3"> </div>
                            <div class="col-md-2">
                                <!-- small box -->
                                <div class="small-box bg-info" style="background-color: #fff!important;">

                                    <button type="button" class="btn btn-default"role="link" onclick="window.location='notification.html'">
                                        Notifications
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <!-- small box -->
                                <div class="small-box bg-info" style="background-color: #fff!important;">
                                    <button type="button" class="btn btn-default" role="link" onclick="window.location='setting.html'">
                                        Setting
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <!-- small box -->
                                <div class="small-box bg-info" style="background-color: #fff!important;">

                                </div>
                            </div>
                            <div class="col-md-3"> </div>
                        </div>
                    </div>
                    <!-- /.row -->
                    <!-- Main row -->
                </div>
            </section>
        </div>
{% endblock %}