lecesse/base/urls.py
from django.conf.urls import url

from . import views

app_name = 'base'

urlpatterns = [
    #principal view
    url('index/', views.index, name='index'),
]

lecesse/lecesse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #direcciones del modulo base
    path('', include('base.urls')),
    #direcciones del modulo users
    path('users/', include('users.urls')),
    #direcciones del modulo phase one
    path('phase_one/', include('phase_one.urls')),
    #direcciones del modulo phase one
    path('phase_two/', include('phase_two.urls')),
    #redirige al index luego de hacer el login
    path('', RedirectView.as_view(url="/home/index/")),
    # muestra el login de inicio
	path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'),
        name='login'),
	#Logout
	path('logout/', auth_views.LogoutView.as_view(template_name='registration/login.html'),
        name='logout'),
]+ static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

lecesse/phase_two/urls.py
from django.conf.urls import url

from . import views

app_name = 'phase_two'

urlpatterns = [
    #principal view
    url('home/', views.home, name='home'),
    #view category
    url('environments/', views.environment, name='environments'),
    url('edit-enviroment/(?P<id_enviroment>[0-9]+)/$', views.edit_enviroment, name='edit_enviroment'),
    url('delete-enviroment/(?P<id_enviroment>[0-9]+)/$', views.delete_enviroment, name='delete_enviroment'),
    url('view-enviroment/(?P<id_enviroment>[0-9]+)/$', views.view_enviroment, name='view_enviroment'),

    #view materials
    url('model_apartment/', views.model_apartment, name='model_apartment'),
    url('create_apartment/', views.create_apartment, name='create_apartment'),
    url('create_apartment_tree/', views.create_apartment_tree, name='create_apartment_tree'),
    url('create_apartment_finish/', views.create_apartment_finish, name='create_apartment_finish'),
    url('edit-apartment/(?P<id_apartment>[0-9]+)/$', views.edit_apartment, name='edit_apartment'),
    url('delete-apartment/(?P<id_apartment>[0-9]+)/$', views.delete_apartment, name='delete_apartment'),
    url('view_apartment/(?P<id_apartment>[0-9]+)/$', views.view_apartment, name='view_apartment'),


    #view providers
    url('project/', views.project, name='project'),
    url('create_pro/', views.create_pro, name='create_pro'),
    url('edit-pro/(?P<id_project>[0-9]+)/$', views.edit_pro, name='edit_pro'),
    url('delete-pro/(?P<id_project>[0-9]+)/$', views.delete_pro, name='delete_pro'),
    url('view_pro/(?P<id_project>[0-9]+)/$', views.view_pro, name='view_pro'),

    #contact
    url('create_cont/', views.create_cont, name='create_cont'),



    url('create_building/', views.create_building, name='create_building'),

    url('finish_pro/', views.finish_pro, name='finish_pro'),

]

lecesse/phase_two/models.py
from django.db import models
from phase_two.choices import *
from phase_one.models import *


class Environment(models.Model):
    name = models.CharField(max_length=100, null=False)
    description = models.CharField(max_length=150, null=False)
    measured_type = models.CharField(max_length=100, null=False, choices=MEASURED_TYPE)
    area_total = models.CharField(max_length=150, null=False)
    icon = models.ImageField(upload_to='environment')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Apto_Model(models.Model):
    name = models.CharField(max_length=100, null=True)
    identifier = models.CharField(max_length=150, null=True)
    flat = models.ImageField(upload_to='model_apto')
    cover_page = models.ImageField(upload_to='model_apto')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class various(models.Model):
    type_measure = models.CharField(max_length=100, null=True,  choices=MEASURED_TYPE)
    area = models.CharField(max_length=150, null=True)
    price = models.CharField(max_length=150, null=True)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Project(models.Model):
    name_project = models.CharField(max_length=100, null=False)
    address = models.CharField(max_length=150, null=False)
    city = models.CharField(max_length=150, null=False)
    state = models.CharField(max_length=150, null=False)
    zip_code = models.CharField(max_length=150, null=False)
    owner_project = models.CharField(max_length=150, null=False)
    utility = models.CharField(max_length=150, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name_project


class Contact(models.Model):
    first_name = models.CharField(max_length=100, null=False)
    last_name = models.CharField(max_length=100, null=False)
    phone_number = models.CharField(max_length=100, null=False)
    position = models.CharField(max_length=100, null=False)
    email = models.EmailField(unique=True,max_length=40)
    id_project = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.first_name

class Building(models.Model):
    number_builings = models.CharField(max_length=100, null=False)
    number_floors = models.CharField(max_length=100, null=False)
    id_project = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.number_builings

lecesse/phase_two/views.py
from django.shortcuts import render, redirect
from phase_two.models import *
from phase_two.forms import EnvironmentsForm, Environments_Edit_Form, \
    Model_Apto_Form_First, Project_Edit_Form, \
    ProjectForm, Edit_Model_Apto_Form, Contact_Form, Building_Form, Various_Form
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login/')
def home(request):
    """show phase one view"""
    projects = Project.objects.all()
    return render(request, 'index_phase_two.html',{'projects':projects})

@login_required(login_url='/login/')
def environment(request):
    """show phase one view"""
    environments = Environment.objects.all()
    if request.method == 'POST':
        form_environment = EnvironmentsForm(request.POST, request.FILES)
        if form_environment.is_valid():
            form_environment.save()
            return redirect('/phase_two/environments/')
        else:
            return render(request, 'environments.html', {'form_environment': form_environment, 'environments': environments})
    else:
        form_environment = EnvironmentsForm()
        return render(request, 'environments.html', {'form_environment': form_environment, 'environments': environments})

@login_required(login_url='/login/')
def edit_enviroment(request, id_enviroment):
    """can edit a enviroment"""
    enviroment = Environment.objects.get(pk=id_enviroment)

    if request.method == 'GET':
        # Get se usa para obtener datos y Post para enviar datos
        form = Environments_Edit_Form(instance=enviroment)
    else:
        # Aqui guardamos el cliente
        form = Environments_Edit_Form(request.POST, instance=enviroment)
        if form.is_valid():
            form.save()
            return redirect('/phase_two/environments/')
    return render(request, 'edit_environment.html', {'form': form})

@login_required(login_url='/login/')
def view_enviroment(request, id_enviroment):
    """can view data enviroment"""
    enviroment = Environment.objects.get(pk=id_enviroment)
    return render(request, 'view_environment.html', {'enviroment': enviroment})

@login_required(login_url='/login/')
def delete_enviroment(request, id_enviroment):
    """delete a enviroment"""
    enviroment = Environment.objects.get(pk=id_enviroment)
    enviroment.delete()
    return redirect('/phase_two/environments/')

@login_required(login_url='/login/')
def model_apartment(request):
    """show phase one view"""
    apartments = Apto_Model.objects.all()
    return render(request, 'model_apartment.html',{'apartments':apartments})


@login_required(login_url='/login/')
def create_apartment(request):
    """show phase one view"""
    environments = Environment.objects.all()
    if request.method == 'POST':
        form_apto = Model_Apto_Form_First(request.POST, request.FILES)
        if form_apto.is_valid():
            form_apto.save()
            print("entro")
            return render(request, 'form_create_model_apto_two.html',
                          {'environments':environments})
        else:
            print("no valido")
            return render(request, 'form_create_model_apto.html',
                          {'form_apto': form_apto})
    else:
        form_apto = Model_Apto_Form_First()
        return render(request, 'form_create_model_apto.html',
                      {'form_apto': form_apto})


@login_required(login_url='/login/')
def create_apartment_tree(request):
    """show phase one view"""
    environments = Material.objects.all()
    form = Various_Form()
    return render(request, 'form_create_model_apto_tree.html', {'form': form, 'environments':environments})

@login_required(login_url='/login/')
def create_apartment_finish(request):
    """show phase one view"""
    return render(request, 'finish_model_apto.html')

@login_required(login_url='/login/')
def edit_apartment(request, id_apartment):
    """can edit a enviroment"""
    apartment = Apto_Model.objects.get(pk=id_apartment)

    if request.method == 'GET':
        # Get se usa para obtener datos y Post para enviar datos
        form = Edit_Model_Apto_Form(instance=apartment)
    else:
        # Aqui guardamos el cliente
        form = Edit_Model_Apto_Form(request.POST, instance=apartment)
        if form.is_valid():
            form.save()
            return redirect('/phase_two/model_apartment/')
    return render(request, 'edit_apartment.html', {'form': form})

@login_required(login_url='/login/')
def view_apartment(request, id_apartment):
    """can view data enviroment"""
    apartment = Apto_Model.objects.get(pk=id_apartment)
    return render(request, 'view_apartment.html', {'apartment': apartment})

@login_required(login_url='/login/')
def delete_apartment(request, id_apartment):
    """delete a enviroment"""
    apartment = Apto_Model.objects.get(pk=id_apartment)
    apartment.delete()
    return redirect('/phase_two/model_apartment/')


@login_required(login_url='/login/')
def project(request):
    """show phase one view"""
    projects = Project.objects.all()
    return render(request, 'project.html', {'projects': projects})


@login_required(login_url='/login/')
def create_pro(request):
    """create a project"""
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save()
            request.session['id_project'] = project.id
            return redirect('/phase_two/create_cont/')
        else:
            return render(request, 'create_project.html', {'form': form})
    else:
        form = ProjectForm()
        return render(request, 'create_project.html', {'form': form})


@login_required(login_url='/login/')
def create_cont(request):
    """can view data enviroment"""
    contacts = Contact.objects.all()
    if request.method == 'POST':
        form = Contact_Form(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print("guardo")
            id_project = request.session.get('id_project')
            contact = Contact(
                first_name=data['first_name'],
                last_name=data['last_name'],
                phone_number=data['phone_number'],
                position=data['position'],
                email=data['email'],
                id_project=id_project
            )
            contact.save()
            return redirect('/phase_two/create_cont/')
        else:
            print("No valido form")
            return render(request, 'create_contact.html', {'form_contact': form})
    else:
        form_contact = Contact_Form()
        print("Entro a crear cont")
        return render(request, 'create_contact.html', {'form_contact': form_contact, 'contacts': contacts })



@login_required(login_url='/login/')
def view_pro(request, id_project):
    """can view data enviroment"""
    project = Project.objects.get(pk=id_project)
    return render(request, 'view_project.html', {'project': project})

@login_required(login_url='/login/')
def edit_pro(request, id_project):
    """can edit a enviroment"""
    project = Project.objects.get(pk=id_project)
    if request.method == 'GET':
        # Get se usa para obtener datos y Post para enviar datos
        form = Project_Edit_Form(instance=project)
    else:
        # Aqui guardamos el cliente
        form = Project_Edit_Form(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('phase_two/project/')
    return render(request, 'edit_project.html', {'form': form})

@login_required(login_url='/login/')
def delete_pro(request, id_project):
    """delete a category"""
    project = Project.objects.get(pk=id_project)
    project.delete()
    return redirect('phase_two/project/')


@login_required(login_url='/login/')
def create_building(request):
    """delete a category"""
    if request.method == 'POST':
        form = Building_Form(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print("guardo")
            id_project = request.session.get('id_project')
            building = Building(
                number_builings=data['number_builings'],
                number_floors=data['number_floors'],
                id_project=id_project,
            )
            building.save()
            return redirect('/phase_two/finish_pro/')
        else:
            print("No valido form")
            return render(request, 'create_building.html', {'form_contact': form})
    else:
        form_contact = Building_Form()
        print("Entro a crear cont")
        return render(request, 'create_building.html', {'form_contact': form_contact})



@login_required(login_url='/login/')
def finish_pro(request):
    """delete a category"""
    id_project = request.session.get('id_project')
    project = Project.objects.get(id=id_project)
    print(project)
    contact = Contact.objects.filter(id_project=id_project)
    building = Building.objects.filter(id_project=id_project)
    return render(request, 'finish_project.html', {'project':project,
                                                   'contact':contact,
                                                   'building':building})

lecesse/phase_two/templates/environments.html
{% extends 'base_phase_two.html' %}
{% block form %}
<div class="card-body mt-5 p-0">
                                <div class="row">
                                    <div class="col-md-4 ">
                                        <form role="form" method="post" enctype="multipart/form-data">
                                             {% csrf_token %}
                                            <div class="row">
                                                <div class="col-sm-10">
                                                    <b class="text-center" style="color: #000;">Create
                                                        environments</b>
                                                    <div class="form-group mt-3">
                                                        {{ form_environment.name }}
                                                    </div>
                                                    <div class="form-group">
                                                        {{ form_environment.description }}
                                                    </div>
                                                    <div class="form-group">
                                                        {{ form_environment.measured_type }}
                                                    </div>
                                                    <div class="form-group"  id="infoGroup">
                                                        <div class="input-group">
                                <div class="input-group-prepend">
                                    <span style="font-size: .85rem !important;">Area&nbsp;</span>
                                </div>
                                <div class="input-group-prepend">
                                    <input type="text" size=1 class="form-control monto" name="Precio" id="Precio" value="" onkeyup="multi();">
                                    <span>&nbsp;x&nbsp;</span>
                                    <input type="text" size=1 class="form-control monto" name="Cantidad" id="Cantidad" onkeyup="multi();">
                                </div><span>&nbsp;=&nbsp;</span>
                                      <input type="hidden" name="area_total" id="area_total">
                                 <label id="Resultado">
                                 </label>
                            </div>
                                                    </div>


                                                    <div class="custom-file">
                                                        {{ form_environment.icon }}
                                                    </div>

                                                    <button type="submit"
                                                        class="btn btnCategory mt-4">Create</button>
                                                </div>
                                                <div class="col-sm-2"></div>
                                            </div>

                                        </form>
                                    </div>
                                    <div class="col-md-8">
                                        <p class="text-right"><button class="btn btn-flat btn-sm" style="background: #D58017;color: #fff;">Exportar</button></p>
                                        <table class="table table-striped projects mt-3" style="background:#ffffff;">
                                            <thead>
                                                <tr>
                                                    <th style="width: 5%">
                                                        ID
                                                    </th>
                                                    <th style="width: 10%">
                                                        Icon
                                                    </th>
                                                    <th style="width: 25%">
                                                        Environments
                                                    </th>
                                                    <th style="width: 30%">
                                                        Description
                                                    </th>

                                                    <th style="width: 30%">
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>

                        {% for environment in environments %}
                        <tr>
                        <td>
                            {{ forloop.counter}}
                        </td>
                        <td>
                           {{ environment.icon}}
                        </td>
                        <td>
                           {{ environment.name}}
                        </td>
                        <td>
                            {{ environment.description}}
                        </td>

                         <td class="project-actions text-right">
                             <a class="btn btn-info btn-sm" href="{% url 'phase_two:view_enviroment' environment.id  %}">
                                 <i class="fas fa-eye" style="color: #ffffff;">
                                 </i>
                             </a>
                             <a class="btn btn-info btn-sm" href="{% url 'phase_two:edit_enviroment' environment.id  %}">
                                 <i class="fas fa-pencil-alt" style="color: #ffffff;">
                                 </i>
                             </a>
                             <a class="btn btn-danger btn-sm" href="{% url 'phase_two:delete_enviroment' environment.id  %}">
                                 <i class="fas fa-trash" style="color: #ffffff;">
                                 </i>
                             </a>
                            </td>
                            </tr>
                        {% endfor %}

                                            </tbody>
                                        </table>
                                        <div class="row">
                                            <div class="col-sm-12 col-md-12">
                                                <div class="dataTables_paginate paging_simple_numbers"
                                                    id="example1_paginate">
                                                    <ul class="pagination">
                                                        <li class="paginate_button page-item previous disabled"
                                                            id="example1_previous">
                                                            <a href="#" aria-controls="example1" data-dt-idx="0"
                                                                tabindex="0" class="page-link">
                                                                Previous
                                                            </a>
                                                        </li>
                                                        <li class="paginate_button page-item active">
                                                            <a href="#" aria-controls="example1" data-dt-idx="1"
                                                                tabindex="0" class="page-link">
                                                                1
                                                            </a>
                                                        </li>
                                                        <li class="paginate_button page-item ">
                                                            <a href="#" aria-controls="example1" data-dt-idx="2"
                                                                tabindex="0" class="page-link">
                                                                2
                                                            </a>
                                                        </li>
                                                        <li class="paginate_button page-item next" id="example1_next">
                                                            <a href="#" aria-controls="example1" data-dt-idx="7"
                                                                tabindex="0" class="page-link">
                                                                Next
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
function multi(){
    var total = 1;
    var change= false; //
    $(".monto").each(function(){
        if (!isNaN(parseFloat($(this).val()))) {
            change= true;
            total *= parseFloat($(this).val());
        }
    });

    total = (change)? total:0;
    document.getElementById('Resultado').innerHTML = total;
    $("#area_total").val(total);
}
</script>
{% endblock %}

lecesse/phase_two/templates/model_apartment.html
{% extends 'base_phase_two.html' %}
{% block form %}
<div class="row mt-5 mb-4">
                                <div class="col-md-3 text-left">
                                    <button type="button" class="btn btn-block btn-success btnWidht"><a href="{% url 'phase_two:create_apartment' %}">Create Model Apartment</a></button>
                                </div>
                                <div class="col-md-3 text-left"></div>
                                <div class="col-md-4 text-left"></div>
                                <div class="col-md-2 text-right">
                                    <button type="button" class="btn btn-block btn-secondary btn-sm btnWidhtTwo">Import</button>
                                </div>
                            </div>

                            <table class="table table-striped projects mt-3" style="background:#ffffff;">
                                <thead>
                                    <tr>
                                        <th style="width: 25%">
                                            Model Apartment Name
                                        </th>
                                        <th style="width: 25%">
                                            Identifier
                                        </th>
                                        <th style="width: 25%">
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>

                        {% for apartment in apartments %}
                         <tr>
                        <td>
                           {{ apartment.name}}
                        </td>
                        <td>
                           {{ apartment.identifier}}
                        </td>
                         <td class="project-actions text-right">
                             <a class="btn btn-info btn-sm" href="{% url 'phase_two:view_apartment' apartment.id  %}">
                                 <i class="fas fa-eye" style="color: #ffffff;">
                                 </i>
                             </a>
                             <a class="btn btn-info btn-sm" href="{% url 'phase_two:edit_apartment' apartment.id  %}">
                                 <i class="fas fa-pencil-alt" style="color: #ffffff;">
                                 </i>
                             </a>
                             <a class="btn btn-danger btn-sm" href="{% url 'phase_two:delete_apartment' apartment.id  %}">
                                 <i class="fas fa-trash" style="color: #ffffff;">
                                 </i>
                             </a>
                            </td>
                             </tr>
                        {% endfor %}

                                </tbody>
                            </table>
{% endblock %}

lecesse/phase_two/templates/project.html
{% extends 'base_phase_two.html' %}
{% block form %}
<div class="row mt-5 mb-4">
                                <div class="col-md-3 text-left">
                                    <button class="btn btn-block btn-success btnWidht"><a href="{% url 'phase_two:create_pro' %}">Create Project</a></button>
                                </div>
                                <div class="col-md-3 text-left"></div>
                                <div class="col-md-4 text-left"></div>
                                <div class="col-md-2 text-right">
                                    <button type="button" class="btn btn-block btn-secondary btn-sm btnWidhtTwo">Import</button>
                                </div>
                            </div>
<div>
                            <table class="table table-striped projects mt-3" style="background:#ffffff;">
                                <thead>
                                    <tr>
                                        <th style="width: 25%">
                                            Name
                                        </th>
                                         <th style="width: 25%">
                                            State
                                        </th>
                                        <th style="width: 25%">
                                            City
                                        </th>
                                         <th style="width: 25%">
                                            Owner Product
                                        </th>
                                        <th style="width: 25%">
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>

                        {% for project in projects %}
                        <tr>
                        <td>
                            {{ project.name_project}}
                        </td>
                        <td>
                            {{ project.state}}
                        </td>
                        <td>
                            {{ project.city}}
                        </td>
                         <td>
                            {{ project.owner_project}}
                        </td>
                         <td class="project-actions text-right">
                             <a class="btn btn-info btn-sm" href="{% url 'phase_two:view_pro' project.id  %}">
                                 <i class="fas fa-eye" style="color: #ffffff;">
                                 </i>
                             </a>
                             <a class="btn btn-info btn-sm" href="{% url 'phase_two:edit_pro' project.id  %}">
                                 <i class="fas fa-pencil-alt" style="color: #ffffff;">
                                 </i>
                             </a>
                             <a class="btn btn-danger btn-sm" href="{% url 'phase_two:delete_pro' project.id  %}">
                                 <i class="fas fa-trash" style="color: #ffffff;">
                                 </i>
                             </a>
                            </td>
                                        </tr>
                        {% endfor %}

                                </tbody>
                            </table>
    </div>
{% endblock %}